
# This file tells Spring Boot/JPA how to connect to your  
    # PostgreSQL database and how Hibernate/JPA should behave.

spring.application.name=task-manager-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/task_manager}
    # Where the PostgreSQL database is located: localhost, port 5432, database task_manager
spring.datasource.username=${DB_USER:taskuser}
spring.datasource.password=${DB_PASSWORD}
    # The PostgreSQL username and password Spring uses to connect.
    # ${VAR:default} means "use the env variable, or the default if missing". Passwords get no default, so the app fails loudly instead of using a weak secret.
spring.datasource.password=${DB_PASSWORD:taskpass} 
    # Add the default so you don't need to export every time locally (related to the mvn test)


spring.jpa.hibernate.ddl-auto=update    
    # Hibernate/JPA automatically updates the database schema based on your entity classes
    # with the @Entity which is Task.java

spring.jpa.show-sql=true
    # Shows the SQL statements that JPA/Hibernate executes in the console